// default package
// Generated 24 May, 2018 8:24:48 PM by Hibernate Tools 5.2.6.Final
package model;
/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private EmpId id;

	public Emp() {
	}

	public Emp(EmpId id) {
		this.id = id;
	}

	public EmpId getId() {
		return this.id;
	}

	public void setId(EmpId id) {
		this.id = id;
	}

}
